export const contactPreferencesCopy = {
    title: "How would you like to stay in touch?",
    intro: "These preferences are shared only with Swami Karma Karuna and her support team. They are separate from your newsletter choice.",
    method: "Preferred contact method",
    methods: { email: "Email", voice: "Voice phone", text: "Text phone" },
    email: "Contact email",
    phone: "Phone number, including country code",
    edit: "Edit contact detail",
    contactNote:
        "This is where you prefer a personal reply. Changing it does not change your sign-in email.",
    checkIns: "Personal check-ins",
    none: "None",
    occasional: "Occasional personal check-ins",
    checkInNote:
        "This lets KK know you welcome an occasional check-in. It does not book a call or promise a schedule.",
    photo: "Your private member photo",
    photoNote:
        "Share a photo only if you would like KK and her support team to remember you. Only you, KK and her member administrators can view it. It is not used in comments, shared profiles or outside messages.",
    photoAlt: "Your optional photo shared with KK and support",
    noPhoto: "No private photo shared.",
    choosePhoto: "Choose or replace photo",
    removePhoto: "Remove private photo",
    photoHelp:
        "Choose, drop or paste a still JPEG, PNG or WebP photo. Your photo saves immediately and stays private.",
    photoSaved: "Private photo saved.",
    photoSaving: "Saving private photo…",
    photoError: "Choose a still JPEG, PNG or WebP photo smaller than 2 MB.",
    save: "Save preferences",
    saving: "Saving preferences…",
    saved: "Preferences saved.",
    loading: "Loading your preferences…",
    failed: "Your preferences could not be loaded. Try again.",
    saveFailed: "Preferences could not be saved. Your changes are still here.",
    retry: "Try again",
    reload: "Reload saved preferences",
    readOnly: "Shared preferences are read-only in Member Mimic.",
    newsNote:
        "News is optional. Sign-in codes, receipts and essential service messages continue when news is off.",
    newsSaved: "Newsletter preference saved.",
    newsSaving: "Saving newsletter preference…",
    newsSave: "Save newsletter preference",
    unsubscribeTitle: "You’re unsubscribed from news",
    unsubscribeBody:
        "You will no longer receive newsletter emails. Sign-in codes, receipts and essential service messages continue.",
    unsubscribeReturn: "Return to the website",
    unsubscribeHelp: "Need help? Contact KK’s support team",
    unsubscribeFailedTitle: "We couldn’t confirm your unsubscribe",
    unsubscribeFailedBody:
        "Your newsletter choice has not been confirmed. Try reopening the link, or contact the support team for help.",
} as const;
