export const helpStyles = `
.kk-help{max-width:1080px;margin:0 auto;padding:64px 24px 72px;color:#312110;font-family:var(--font-open-sans),"Open Sans",sans-serif;font-size:17px;line-height:1.7}
.kk-help h1,.kk-help h2,.kk-help h3{font-family:var(--font-playfair-display),"Playfair Display",Georgia,serif;line-height:1.25;color:inherit}
.kk-help h1{font-size:clamp(2.1rem,5vw,3.6rem);max-width:760px;margin:16px 0 24px}.kk-help h2{font-size:2rem}.kk-help h3{font-size:1.55rem;margin:0 0 20px}
.kk-help p{margin:0 0 20px;max-width:72ch}.kk-help a{color:#993300;text-decoration:underline;text-underline-offset:4px}.kk-help a:focus-visible,.kk-help button:focus-visible,.kk-help input:focus-visible{outline:3px solid #216097;outline-offset:5px}
.kk-help-nav{display:flex;gap:12px 24px;flex-wrap:wrap;font-size:1rem;margin-bottom:32px}.kk-help-nav [aria-current=page]{font-weight:700}
.kk-help-controls{display:flex;align-items:end;flex-wrap:wrap;gap:24px;margin:36px 0 12px}.kk-help-search{display:grid;gap:8px;flex:1;min-width:220px}.kk-help-search input{box-sizing:border-box;width:100%;border:1px solid #9c7f52;border-radius:8px;padding:12px;background:#fff;color:#312110;font:inherit}
.kk-help button,.kk-help-action{font:inherit;border:1px solid #993300;border-radius:8px;background:#fffaf0;color:#993300;padding:10px 16px;cursor:pointer}.kk-help button[aria-pressed=true],.kk-help-action{background:#993300;color:#fff}.kk-help-actions{display:flex;flex-wrap:wrap;gap:12px 20px;align-items:center}.kk-help-actions .kk-help-action{color:#fff;text-decoration:none;display:inline-block}
.kk-help-mode{display:flex;gap:8px}.kk-help-hint{font-size:.95rem;color:#62533d}.kk-policy-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;margin:28px 0 40px}.kk-policy-card{padding:32px;border:1px solid #cbbda5;border-radius:14px;background:#fffdf8;min-width:0}.kk-policy-card p{white-space:pre-line}.kk-policy-card button{font-size:.95rem;margin-top:8px}.kk-help-note{border-top:1px solid #cbbda5;padding-top:32px;margin-top:40px}.kk-help-panel{padding:32px;border:1px solid #cbbda5;border-radius:14px;background:#fffdf8;margin:28px 0}
@media(max-width:680px){.kk-help{padding:40px 20px 52px}.kk-policy-grid{grid-template-columns:1fr}.kk-policy-card,.kk-help-panel{padding:24px}.kk-help-controls{align-items:stretch}.kk-help-mode{flex-wrap:wrap}}
@media(prefers-color-scheme:dark){.dark .kk-help{color:#f7f4eb}.dark .kk-policy-card,.dark .kk-help-panel{background:#211c16;border-color:#9c7f52}.dark .kk-help a{color:#ffbc69}.dark .kk-help-hint{color:#d9cdb8}.dark .kk-help-actions .kk-help-action{color:#fff}}
@media print{.kk-help{max-width:none;padding:0;color:#000;font-size:12pt}.kk-help-nav,.kk-help-controls,.kk-help-hint,.kk-policy-card button,.kk-help-actions{display:none!important}.kk-policy-grid{display:block}.kk-policy-card[hidden],.kk-policy-card{display:block!important;break-inside:avoid;page-break-inside:avoid;margin:0 0 20pt;padding:16pt;border:1px solid #777;background:#fff!important}.kk-policy-card h3{color:#000}.kk-policy-summary{display:none!important}.kk-policy-full[hidden],.kk-policy-full{display:block!important}.kk-help a{color:#000}.kk-help-note{margin-top:20pt}}
`;
